version: '2'
services:
  postgis:
    build: ../postgis
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ../pg_sockets:/var/run/postgresql/
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=gis
      - POSTGRES_PASS=passwd
      - HSTORE=true
      - PGDATA=/var/lib/postgresql/data
  imp_osm_carto:
    build: ../imp_osm_carto
    volumes:
      - ../shared_volume:/opt/shared
    environment:
      - PGPASS=passwd
  imp_stamen_terrain:
    build: ../imp_stamen_terrain
    volumes:
      - ../shared_volume:/opt/shared
    environment:
      - PGPASS=passwd
  rendering:
    build: ../rendering
    volumes:
      - ../shared_volume:/opt/shared
      - ../pg_sockets:/var/run/postgresql/
    environment:
      - PGPASS=passwd
    ports:
      - "6789:6789"
      - "8080:8080"
volumes:
  pg_data: {}
